"""Add detailed property information and image galleries

Revision ID: b31ac82d7533
Revises: 
Create Date: 2023-10-22 17:38:39.123456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b31ac82d7533'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bedrooms', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bathrooms', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('area', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('amenities', sa.Text(), nullable=True))

    op.create_table('gallery_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=200), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gallery_image')
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_column('amenities')
        batch_op.drop_column('area')
        batch_op.drop_column('bathrooms')
        batch_op.drop_column('bedrooms')
    # ### end Alembic commands ###